server:
  port: 9091

spring:
  application:
    name: GREET-API

  output:
    ansi:
      enabled: ALWAYS  # Enables colored terminal logs

  kafka:
    admin:
      client:
        url: "http://localhost:1111/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
