server:
  port: 8081

spring:
  application:
    name: WELCOME-API

  output:
    ansi:
      enabled: ALWAYS

  boot:
    admin:
      client:
        url: http://localhost:1111
        
      instance:
        service-base-url: http://localhost:8081
        health-url: http://localhost:8081/actuator/health
        management-url: http://localhost:8081/actuator

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true  # Optional: Useful if deployed with IP

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
